[theme]
# Primary accent color for interactive elements.
#primaryColor = "#d33682"
primaryColor = "#838996"

# Background color for the main content area.
#backgroundColor = "#002b36"
backgroundColor = "#E5E4E2"

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = "#586e75"
#secondaryBackgroundColor = "#838996"
secondaryBackgroundColor = "#F5F5F5"

# Color used for almost all text.
textColor = "#262626"

[client]
#toolbarMode = "minimal"
showSidebarNavigation = false